title: BRANDED
description: A website with a blog
header_text: Branded
footer_text: Copyright 2020 Isabelle Wendes
header_feature_image: ../uploads/branded-final-logo-cropped.png
bannerheight: 60vmax
logo: ../uploads/branded-final-logo-cropped.png
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
