title: BRANDED
description: A website with a blog
header_text: ""
footer_text: Copyright 2020 Isabelle Wendes
header_feature_image: ../uploads/branded-final-logo-scaled.png
bannerheight: 100vh
logo: ../uploads/favicon-cropped.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About Me
    siteurl: /aboutme
    tab: false
  - siteurl: /challemges
    tab: true
    name: "!"
